### ISSUE TITLE
exec format error under arm64

### ISSUE THREAD

**Issue by volker76** [volker76/tuya_mqtt.net#11]
executing `docker run --rm -v /tuya_data:/app/DataDir  -p 9999:80 -p 6667:6667/UDP -p 6666:6666/UDP --name my_tuya_mqtt_client volkerhaensel/tuya_mqtt.net`
in a arm64 instance results in 
**exec /usr/bin/dotnet: exec format error**

**Comment by volker76** [comment]
fixed with [v1.0.3](https://github.com/volker76/tuya_mqtt.net/releases/tag/v1.0.3)

**Comment by maddhin** [comment]
working! Thanks for the quick fix!

**Comment by volker76** [comment]
I should have tested this already in the first place – I’m using x64 docker and this is what GITHUB creates natively.
Feel free to enter in further issues and feature requests…

Volker

Von: Martin ***@***.***>
Gesendet: Samstag, 4. November 2023 21:20
An: volker76/tuya_mqtt.net ***@***.***>
Cc: Volker Hänsel ***@***.***>; State change ***@***.***>
Betreff: Re: [volker76/tuya_mqtt.net] exec format error under arm64 (Issue #11)


working! Thanks for the quick fix!
