### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by maddhin** [volker76/tuya_mqtt.net#15]
Hi, I want to recommend the following GUI and functional improvements:

1.) under Tuya Devices -> Scanned network devices: 
- add a button to manually search for new devices (in my case new devices do not show automatically in the overview)
- add the device name for easier identification of the device

2.) under Tuya devices -> Connected Devices & Data
- add the device name (also see feature request [https://github.com/volker76/tuya_mqtt.net/issues/14])

3.) under Log
- add time stamps

**Comment by volker76** [comment]
I really appreaciate the feedback and imporvement request. But I need to close this here as we only can handle one particular issue in one ticket and need to open multiple cases to allow us discussing the cases and work on the omprovements.
