### ISSUE TITLE
exec /usr/bin/dotnet: exec format error

### ISSUE THREAD

**Issue by maddhin** [volker76/tuya_mqtt.net#9]
Hi,

I am running docker on a RPI4 and are getting the following error message when starting the container:

exec /usr/bin/dotnet: exec format error

Can anybody point me in the right direction, where the problem might be? :) Cheers!!!

**Comment by volker76** [comment]
I would like to reproduce the issue, you run the RPI with arm32 or arm64 linux?

**Comment by volker76** [comment]
tested successfully under a RPI-4 Model B (2018)
Linux version 5.15.84-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1613 SMP Thu Jan 5 12:01:26 GMT 2023

**Comment by maddhin** [comment]
Hi Volker, I'm running on Raspbian 11 32bit on arm v7 / Rpi4. Latest Docker & docker-compose.

**Comment by volker76** [comment]
seems not RPI4 reladed, can reproduce under another arm64 instance - would handle this with issue #11

**Comment by volker76** [comment]
@maddhin the issue seems reproducable and it seems to be caused by some cross-platform docker build issues with dotnet and QEMU. you can try pulling the docker image **volkerhaensel/tuya_mqtt.net:arm64_issue-11**  this worked for me under x64,arm64 and arm/v7
